server:
  model: debug
  port: 18080
  image_path: public/images

logger:
  # 日志级别
    # debug -1
    # info  0
    # warn  1
    # error 2
    # dPanic 3
    # panic 4
    # fatal 5
  level: -1
  file_path: ./log/log.log

# session配置
session:
  # session过期时间
  expire: 3600
  # secret
  secret: "GoPure"

# 数据库配置
datasource:
  host: 127.0.0.1
  port: 3306
  username: GoPure
  password: 123456
  db_name: GoPure
  table_prefix: "p_"
  log_mode: true
