server:
  model: debug
  port: 8081

logger:
  # 日志级别
    # debug -1
    # info  0
    # warn  1
    # error 2
    # dPanic 3
    # panic 4
    # fatal 5
  level: -1
  file_path: ./log/log.log

# 数据库配置
datasource:
  host: 111.229.136.223
  port: 3306
  username: GoPure
  password: DwAsfwRWhHP62W3K
  db_name: GoPure
  table_prefix: "p_"
  log_mode: true
